# Generated by Django 3.2.2 on 2023-07-06 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230706_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
