# Generated by Django 3.2.2 on 2023-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pdf_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='guest_code',
            field=models.CharField(blank=True, default='rVPI86', max_length=6),
        ),
    ]
