# Generated by Django 3.2.2 on 2023-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pdf_guest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='guest_code',
            field=models.CharField(blank=True, default='TGbcAX', max_length=6),
        ),
    ]
