# Generated by Django 3.2.2 on 2023-07-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230708_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='guest_code',
            field=models.CharField(blank=True, default='TP4050', max_length=6),
        ),
    ]
