# Generated by Django 3.2.2 on 2023-07-08 07:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230708_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='guest_code',
            field=models.CharField(blank=True, default='qt84ZX', max_length=6),
        ),
    ]
